spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  profiles:
    active: dev
  cache:
    jcache:
      config: classpath:ehcache.xml
---
# The dev profile will use
# 1. localhost to connect to inventory service
# 2. H2 In memory database for storing data
spring:
  profiles: dev
cleon:
  products:
    inventory-service-host: 'http://localhost:8081'

---
# The qa profile will use
# 1. localhost to connect to inventory service
# 2. Oracle database for storing data
spring:
  profiles: qa
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: CLEON_PRODUCTS
    password: CLEON_PRODUCTS
  jpa:
    hibernate:
      ddl-auto: none
cleon:
  products:
    inventory-service-host: 'http://localhost:8081'

---
spring:
  profiles: prod
cleon:
  products:
    inventory-service-host: 'http://cleon-products-inventory:8081'