spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  profiles:
    active: local
  cache:
    jcache:
      config: classpath:ehcache.xml
---
spring:
  profiles: local
cleon:
  products:
    inventory-service-host: 'http://localhost:8081'

---
spring:
  profiles: cloud
cleon:
  products:
    inventory-service-host: 'http://cleon-products-inventory:8081'